theme: jekyll-theme-minimal
title: Carte des parrainages des maires de France
description: Carte des parrainages des maires de France. Les donnees viennent du conseil constitutionnel https://presidentielle2022.conseil-constitutionnel.fr/les-parrainages/tous-les-parrainages-valides.html
logo: bot.png
